### ISSUE TITLE
Windows tests broken?

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#4422]
I made a small change in #4421 to a couple of regexps and the Windows CI tests are failing. Is this a problem with the CI environment?

![Image](https://github.com/user-attachments/assets/9e3b1e1a-25cb-466d-99bb-ecda9e0bfd6d)

**Comment by casey** [comment]
Not that I know of. I just merged #4423 and all the Windows tests passed.

**Comment by gmart7t2** [comment]
Something weird is going on. The tests keep failing for me and not for you or raph:

![Image](https://github.com/user-attachments/assets/b1bcea2f-f96f-49ff-8e9b-e830ee630e1f)
![Image](https://github.com/user-attachments/assets/aa7c64d5-1db1-4669-b19d-675918f98708)

The errors are unrelated to my changes

**Comment by casey** [comment]
Huh, that's very weird. We do see sporadic failures, so it's possible that it's just random that your runs happen to have failed.

**Comment by gmart7t2** [comment]
I made a PR (#4430) that only edited the runes specification markdown `docs/src/runes/specification.md`. It still failed, on the Ubuntu tests this time:

![Image](https://github.com/user-attachments/assets/f426d78c-ac2d-4bcd-8af7-ba484e7fb2ea)

**Comment by gmart7t2** [comment]
Here's how the windows tests failed from my previous PR:

![Image](https://github.com/user-attachments/assets/8d4fdc0b-8cfe-4723-9163-0598cbfe2d97)
